package com.androidapps.nychighschoolslists.fakeresourcesfortest

import com.androidapps.nychighschoolslists.model.SatScoreApiResponseItem
import com.androidapps.nychighschoolslists.model.SchoolListResponseItem

/*Fake school lists for testing*/
class SchoolApiResponseWithScoreFake {


    fun getListOfSchool(): MutableList<SchoolListResponseItem> {
        var school1 = SchoolListResponseItem(
            1,
            "dbn",
            "city1",
            "phone_number1",
            "primary_address_line_1",
            "num_of_sat_test_takers1",
            "sat_critical_reading_avg_score1",
            "sat_math_avg_score1",
            "sat_writing_avg_score1",
            "school_name1",
            "school_email1",
            "latitude1",
            "longitude11",
            "requirement1_11",
            "requirement2_11",
            "requirement3_11",
            "requirement4_11",
            "requirement5_11",
            "website1",
            12345,
            "total_sat_score1",
            123,
            "state_code1",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,

            )
        var school2 = SchoolListResponseItem(
            2,
            "dbn2",
            "city12",
            "phone_number12",
            "primary_address_line_12",
            "num_of_sat_test_takers12",
            "sat_critical_reading_avg_score12",
            "sat_math_avg_score12",
            "sat_writing_avg_score12",
            "school_name12",
            "school_email12",
            "latitude12",
            "longitude112",
            "requirement1_112",
            "requirement2_112",
            "requirement3_112",
            "requirement4_112",
            "requirement5_112",
            "website12",
            123452,
            "total_sat_score12",
            1232,
            "state_code12",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null
        )
        var listOfSchools = mutableListOf<SchoolListResponseItem>(school1, school2)
        return listOfSchools
    }

    fun getListOfScores(): MutableList<SatScoreApiResponseItem> {
        var score1 = SatScoreApiResponseItem("1", "12", "300", "400", "500", "schoolName1")
        var score2 = SatScoreApiResponseItem("2", "13", "400", "500", "600", "schoolName2")
        var score3 = SatScoreApiResponseItem("3", "14", "500", "600", "700", "schoolName2")
        return mutableListOf(score1, score2, score3)
    }
}